# Generated by Django 5.0.1 on 2024-08-21 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
