# Generated by Django 5.0.1 on 2024-08-21 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_publication_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
