# Generated by Django 5.1 on 2024-08-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_publication_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
